global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'webapp'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['webapp:8083']

  - job_name: 'weather-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['weather-service:8080']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
